// Auto-generated by scripts/build-ai-layout-runtime.mjs. Do not edit manually.
module.exports = {
  "shared": {
    "colorPalettes": {
      "version": "2026.03.25-alpha.1",
      "defaultColorPalette": "tech-green",
      "colorPalettes": [
        {
          "id": "tech-green",
          "label": "科技绿",
          "description": "信息卡与案例教程风格，适合产品介绍、操作指南和案例拆解。",
          "recommendedFor": [
            "tutorial",
            "case-study",
            "product-intro"
          ],
          "tokens": {
            "accent": "#14b37d",
            "accentDeep": "#0f8f64",
            "accentSoft": "#e8faf4",
            "text": "#24323d",
            "muted": "#66737f",
            "border": "#dbe7e1",
            "surface": "#ffffff",
            "surfaceSoft": "#f5f8f7",
            "quoteBg": "#f4f7f6"
          }
        },
        {
          "id": "ocean-blue",
          "label": "深海蓝",
          "description": "更冷静的科技信息风格，适合教程、知识卡片和产品更新。",
          "recommendedFor": [
            "tutorial",
            "knowledge-card",
            "release-note"
          ],
          "tokens": {
            "accent": "#2c6bed",
            "accentDeep": "#1f4fb2",
            "accentSoft": "#edf4ff",
            "text": "#223047",
            "muted": "#5e718f",
            "border": "#d8e2f2",
            "surface": "#ffffff",
            "surfaceSoft": "#f6f9fd",
            "quoteBg": "#f2f6fc"
          }
        },
        {
          "id": "sunset-amber",
          "label": "暖砂金",
          "description": "更偏内容杂志感的暖色风格，适合观点、清单和经验分享。",
          "recommendedFor": [
            "essay",
            "checklist",
            "experience"
          ],
          "tokens": {
            "accent": "#d8892b",
            "accentDeep": "#a66218",
            "accentSoft": "#fff5e8",
            "text": "#3a2b1f",
            "muted": "#7b6756",
            "border": "#eadfce",
            "surface": "#fffdf9",
            "surfaceSoft": "#faf6f0",
            "quoteBg": "#f8f2ea"
          }
        },
        {
          "id": "graphite-rose",
          "label": "石墨玫瑰",
          "description": "偏编辑感的灰粉中性色，适合案例拆解和品牌内容。",
          "recommendedFor": [
            "case-study",
            "brand-story",
            "editorial"
          ],
          "tokens": {
            "accent": "#cc5f82",
            "accentDeep": "#9f4764",
            "accentSoft": "#fff0f5",
            "text": "#2e2c33",
            "muted": "#6f6874",
            "border": "#e7dce3",
            "surface": "#fffefe",
            "surfaceSoft": "#faf7f9",
            "quoteBg": "#f8f2f5"
          }
        }
      ]
    },
    "blockCatalog": {
      "version": "2026.03.25-alpha.1",
      "selectionAutoValue": "auto",
      "outputFields": [
        "articleType",
        "selection",
        "resolved",
        "recommendedLayoutFamily",
        "recommendedColorPalette",
        "title",
        "summary",
        "blocks"
      ],
      "blocks": [
        {
          "type": "hero",
          "fields": [
            "eyebrow",
            "title",
            "subtitle",
            "coverImageId",
            "variant"
          ],
          "description": "文章封面卡，适合标题、导语和封面图。"
        },
        {
          "type": "part-nav",
          "fields": [
            "items[{label,text}]"
          ],
          "description": "章节导航卡，适合目录或分段导读。"
        },
        {
          "type": "lead-quote",
          "fields": [
            "text",
            "note"
          ],
          "description": "导语摘要卡，适合金句、总结或开场重点。"
        },
        {
          "type": "case-block",
          "fields": [
            "caseLabel",
            "title",
            "summary",
            "bullets",
            "imageIds",
            "highlight"
          ],
          "description": "案例/教程主体区块，适合分章节承载正文。"
        },
        {
          "type": "section-block",
          "fields": [
            "sectionIndex",
            "sectionLabel",
            "headingLevel",
            "title",
            "paragraphs",
            "bulletGroups",
            "callouts",
            "subsections[{title,level,paragraphs,bulletGroups,callouts}]",
            "imageIds"
          ],
          "description": "正文保真区块，按 sectionIndex 引用原文章节内容，不改写正文；默认由 H2 级主章节承载，H3/H4 留在块内做 subsection，并尽量保留 callout、代码块、表格和嵌套列表等特殊结构。"
        },
        {
          "type": "phone-frame",
          "fields": [
            "imageId",
            "caption"
          ],
          "description": "手机截图展示块，适合 App 界面或聊天截图。"
        },
        {
          "type": "cta-card",
          "fields": [
            "title",
            "body",
            "buttonText",
            "note"
          ],
          "description": "收尾 CTA 区块，适合总结、引导或后续动作。"
        }
      ]
    },
    "wechatSafeStylePrimitives": {
      "version": "2026.03.25-alpha.1",
      "typography": {
        "bodyFontFamily": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"PingFang SC\",\"Hiragino Sans GB\",\"Microsoft YaHei\",sans-serif",
        "editorialDisplayFont": "Georgia,\"Times New Roman\",\"Songti SC\",\"Noto Serif SC\",serif",
        "bodyFontSize": 16,
        "bodyLineHeight": 1.8,
        "paragraphGap": 20,
        "letterSpacing": "0"
      },
      "image": {
        "borderRadius": 14,
        "captionFontSize": 12
      },
      "sectionLabels": {
        "source-first": "Section",
        "tutorial-cards": "SECTION",
        "editorial-lite": "Part"
      },
      "profiles": {
        "source-first": {
          "wrapperPadding": "20px 16px 28px",
          "cardRadius": 10,
          "cardPadding": "0",
          "cardMargin": 8,
          "cardShadow": "none",
          "hero": {
            "eyebrowSize": 11,
            "eyebrowLetterSpacing": 1.2,
            "titleSize": 26,
            "subtitleSize": 16,
            "subtitleLineHeight": 1.8,
            "footerMode": "divider",
            "imageRadius": 18
          },
          "partNav": {
            "gap": 16,
            "direction": "row",
            "useCard": false,
            "useDivider": true
          },
          "leadQuote": {
            "background": "transparent",
            "borderLeft": true,
            "fontSize": 16,
            "fontWeight": 600
          },
          "caseBlock": {
            "useCard": false,
            "indexSize": 22,
            "titleSize": 20
          },
          "subsection": {
            "titleSize": 16,
            "titleWeight": 700,
            "useCard": false,
            "useBorderLeft": true,
            "spacingTop": 14
          }
        },
        "tutorial-cards": {
          "wrapperPadding": "26px 18px 34px",
          "cardRadius": 18,
          "cardPadding": "18px",
          "cardMargin": 18,
          "cardShadow": "0 10px 30px -24px rgba(0,0,0,0.18)",
          "hero": {
            "eyebrowSize": 11,
            "eyebrowLetterSpacing": 1.2,
            "titleSize": 28,
            "subtitleSize": 14,
            "subtitleLineHeight": 1.7,
            "footerMode": "accent-bar",
            "imageRadius": 18
          },
          "partNav": {
            "gap": 10,
            "direction": "row",
            "useCard": true,
            "useDivider": false
          },
          "leadQuote": {
            "background": "quoteBg",
            "borderLeft": false,
            "fontSize": 18,
            "fontWeight": 700
          },
          "caseBlock": {
            "useCard": true,
            "indexSize": 28,
            "titleSize": 22
          },
          "subsection": {
            "titleSize": 15,
            "titleWeight": 700,
            "useCard": true,
            "useBorderLeft": true,
            "spacingTop": 16
          }
        },
        "editorial-lite": {
          "wrapperPadding": "30px 22px 40px",
          "cardRadius": 0,
          "cardPadding": "0",
          "cardMargin": 30,
          "cardShadow": "none",
          "hero": {
            "eyebrowSize": 10,
            "eyebrowLetterSpacing": 2,
            "titleSize": 36,
            "subtitleSize": 17,
            "subtitleLineHeight": 1.88,
            "footerMode": "editorial-divider",
            "imageRadius": 28
          },
          "partNav": {
            "gap": 10,
            "direction": "column",
            "useCard": false,
            "useDivider": true
          },
          "leadQuote": {
            "background": "transparent",
            "borderLeft": false,
            "fontSize": 26,
            "fontWeight": 600
          },
          "caseBlock": {
            "useCard": false,
            "indexSize": 14,
            "titleSize": 26
          },
          "subsection": {
            "titleSize": 18,
            "titleWeight": 600,
            "useCard": false,
            "useBorderLeft": false,
            "spacingTop": 18
          }
        }
      },
      "allowedCssNotes": [
        "仅允许 inline style",
        "优先使用 section/p/figure/img/figcaption/span 等稳定标签",
        "允许有限 flex，但不能依赖复杂 class 选择器",
        "禁止 style 标签与外部 class 驱动样式"
      ]
    },
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "obsidian-wechat-converter/article-layout.schema.json",
      "title": "WeChat Article Layout",
      "type": "object",
      "required": [
        "articleType",
        "title",
        "summary",
        "selection",
        "resolved",
        "blocks"
      ],
      "additionalProperties": false,
      "properties": {
        "articleType": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "selection": {
          "type": "object",
          "required": [
            "layoutFamily",
            "colorPalette"
          ],
          "additionalProperties": false,
          "properties": {
            "layoutFamily": {
              "enum": [
                "auto",
                "source-first",
                "tutorial-cards",
                "editorial-lite"
              ]
            },
            "colorPalette": {
              "enum": [
                "auto",
                "tech-green",
                "ocean-blue",
                "sunset-amber",
                "graphite-rose"
              ]
            }
          }
        },
        "resolved": {
          "type": "object",
          "required": [
            "layoutFamily",
            "colorPalette"
          ],
          "additionalProperties": false,
          "properties": {
            "layoutFamily": {
              "enum": [
                "source-first",
                "tutorial-cards",
                "editorial-lite"
              ]
            },
            "colorPalette": {
              "enum": [
                "tech-green",
                "ocean-blue",
                "sunset-amber",
                "graphite-rose"
              ]
            }
          }
        },
        "recommendedLayoutFamily": {
          "enum": [
            "source-first",
            "tutorial-cards",
            "editorial-lite"
          ]
        },
        "recommendedColorPalette": {
          "enum": [
            "tech-green",
            "ocean-blue",
            "sunset-amber",
            "graphite-rose"
          ]
        },
        "stylePack": {
          "type": "string",
          "description": "兼容旧版本字段；运行时应以 resolved.colorPalette 为准。"
        },
        "blocks": {
          "type": "array",
          "minItems": 1,
          "maxItems": 24,
          "items": {
            "oneOf": [
              {
                "type": "object",
                "required": [
                  "type",
                  "title"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "hero"
                  },
                  "eyebrow": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "subtitle": {
                    "type": "string"
                  },
                  "coverImageId": {
                    "type": "string"
                  },
                  "variant": {
                    "enum": [
                      "cover-right",
                      "cover-left"
                    ]
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type",
                  "items"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "part-nav"
                  },
                  "items": {
                    "type": "array",
                    "maxItems": 6,
                    "items": {
                      "type": "object",
                      "required": [
                        "label",
                        "text"
                      ],
                      "additionalProperties": false,
                      "properties": {
                        "label": {
                          "type": "string"
                        },
                        "text": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type",
                  "text"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "lead-quote"
                  },
                  "text": {
                    "type": "string"
                  },
                  "note": {
                    "type": "string"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "case-block"
                  },
                  "caseLabel": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "summary": {
                    "type": "string"
                  },
                  "bullets": {
                    "type": "array",
                    "maxItems": 6,
                    "items": {
                      "type": "string"
                    }
                  },
                  "imageIds": {
                    "type": "array",
                    "maxItems": 4,
                    "items": {
                      "type": "string"
                    }
                  },
                  "highlight": {
                    "type": "string"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type",
                  "sectionIndex"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "section-block"
                  },
                  "sectionIndex": {
                    "oneOf": [
                      {
                        "type": "integer",
                        "minimum": 0
                      },
                      {
                        "type": "string",
                        "pattern": "^[0-9]+$"
                      }
                    ]
                  },
                  "sectionLabel": {
                    "type": "string"
                  },
                  "headingLevel": {
                    "type": "integer",
                    "minimum": 2,
                    "maximum": 6
                  },
                  "title": {
                    "type": "string"
                  },
                  "paragraphs": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "bulletGroups": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "callouts": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "type": {
                          "type": "string"
                        },
                        "title": {
                          "type": "string"
                        },
                        "body": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "subsections": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "required": [
                        "title"
                      ],
                      "additionalProperties": false,
                      "properties": {
                        "title": {
                          "type": "string"
                        },
                        "level": {
                          "type": "integer",
                          "minimum": 3,
                          "maximum": 6
                        },
                        "paragraphs": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "bulletGroups": {
                          "type": "array",
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          }
                        },
                        "callouts": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "type": {
                                "type": "string"
                              },
                              "title": {
                                "type": "string"
                              },
                              "body": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "imageIds": {
                    "type": "array",
                    "maxItems": 3,
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type",
                  "imageId"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "phone-frame"
                  },
                  "imageId": {
                    "type": "string"
                  },
                  "caption": {
                    "type": "string"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "type"
                ],
                "additionalProperties": false,
                "properties": {
                  "type": {
                    "const": "cta-card"
                  },
                  "title": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  },
                  "buttonText": {
                    "type": "string"
                  },
                  "note": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        }
      }
    },
    "template": {
      "articleType": "tutorial",
      "selection": {
        "layoutFamily": "auto",
        "colorPalette": "auto"
      },
      "resolved": {
        "layoutFamily": "tutorial-cards",
        "colorPalette": "tech-green"
      },
      "recommendedLayoutFamily": "tutorial-cards",
      "recommendedColorPalette": "tech-green",
      "title": "文章标题",
      "summary": "一句摘要",
      "blocks": [
        {
          "type": "hero",
          "eyebrow": "AI Layout Draft",
          "title": "文章标题",
          "subtitle": "封面导语",
          "coverImageId": "image-1",
          "variant": "cover-right"
        },
        {
          "type": "lead-quote",
          "text": "一段适合做导语的重点摘要。",
          "note": "补充说明或上下文。"
        },
        {
          "type": "section-block",
          "sectionIndex": 0,
          "sectionLabel": "PART 01",
          "headingLevel": 2,
          "title": "第一部分",
          "paragraphs": [
            "这里是承接原文章节的正文。"
          ],
          "bulletGroups": [],
          "callouts": [
            {
              "type": "tip",
              "title": "补充提示",
              "body": "这里是保留在 section-block 内的 callout。"
            }
          ],
          "subsections": [
            {
              "title": "子节一",
              "level": 3,
              "paragraphs": [
                "这里是块内 subsection 的正文。"
              ],
              "bulletGroups": [],
              "callouts": [
                {
                  "type": "note",
                  "title": "子节说明",
                  "body": "这里是 subsection 内的 callout。"
                }
              ]
            }
          ],
          "imageIds": [
            "image-1"
          ]
        }
      ]
    },
    "version": "2026.03.25-alpha.1"
  },
  "skills": [
    {
      "id": "source-first",
      "manifest": {
        "id": "source-first",
        "label": "原文增强型",
        "order": 1,
        "version": "2026.03.25-alpha.1",
        "selectionValue": "source-first",
        "defaultColorPalette": "tech-green",
        "promptMode": "source-first",
        "fallbackPolicy": "source-first-preserve",
        "renderProfile": "source-first",
        "allowedBlocks": [
          "hero",
          "part-nav",
          "lead-quote",
          "case-block",
          "section-block",
          "phone-frame",
          "cta-card"
        ],
        "supportsImages": true,
        "providerStrategy": "prefer-ai-fallback-local",
        "recommendedArticleTypes": [
          "article",
          "essay",
          "note",
          "knowledge-base"
        ],
        "description": "最接近普通预览，正文尽量连续流动，只做轻量结构增强。"
      },
      "prompt": "你正在生成“原文增强型”公众号排版。\n\n目标：\n- AI 只做轻量结构增强，不改写作者观点。\n- 正文主体优先使用 section-block，通过 sectionIndex 引用原文章节。\n- 除非原文非常适合，否则不要主动生成教程感很强的 hero、part-nav、phone-frame、cta-card。\n- 如果要给出 lead-quote，优先摘取原文中的导语、观点句或总结句，不要重新写一段新文案。\n- 如果原文章节里已经有 callout、代码块、表格、嵌套列表等特殊结构，优先保留在对应 section-block / subsection 中，不要压平成普通段落。\n\n风格原则：\n- 更像“普通预览的升级版”，不是教程模板。\n- 保留原文节奏和章节顺序。\n- 允许轻微导语增强和图片上提，但不能牺牲正文完整性。",
      "blocks": {
        "preferredIntroBlocks": [
          "lead-quote"
        ],
        "optionalIntroBlocks": [
          "hero",
          "part-nav"
        ],
        "preferredBodyBlocks": [
          "section-block"
        ],
        "optionalBodyBlocks": [
          "case-block"
        ],
        "optionalTailBlocks": [
          "cta-card"
        ],
        "imageStrategy": "conservative"
      },
      "fallback": {
        "includeHero": false,
        "includePartNav": false,
        "includeLeadQuote": true,
        "includePhoneFrame": false,
        "includeCta": false,
        "heroVariant": "cover-right",
        "heroEyebrow": "AI Article Layout",
        "galleryCaseLabel": "GALLERY",
        "galleryTitle": "配图补充",
        "preferSectionBlocks": true,
        "remainingImageStrategy": "sections-first",
        "maxSectionBlocks": 6
      },
      "skillDoc": "---\nname: source-first-layout\ndescription: 原文增强型 skill。强调正文保真、轻量结构增强、AI 失败时本地兜底。\n---\n\n# Source-First Layout Skill\n\n这个 skill 用于把文章排成“最接近普通预览”的公众号版式。\n\n## Guardrails\n\n- 优先使用 `section-block`\n- 不重写正文\n- 不默认追加 CTA\n- 不默认加入教程式导航\n- 图片只做轻度上提，不强行手机壳\n- 原文里的 `callout`、代码块、表格、嵌套列表等特殊结构应尽量保留在对应的 `section-block / subsection` 中，不要压平成普通段落",
      "examples": [
        {
          "name": "article.json",
          "value": {
            "articleType": "article",
            "selection": {
              "layoutFamily": "source-first",
              "colorPalette": "tech-green"
            },
            "resolved": {
              "layoutFamily": "source-first",
              "colorPalette": "tech-green"
            },
            "recommendedLayoutFamily": "source-first",
            "recommendedColorPalette": "tech-green",
            "title": "养好一个孩子，从放过自己开始！",
            "summary": "保留原文节奏，只做轻量增强。",
            "blocks": [
              {
                "type": "lead-quote",
                "text": "先放过自己，很多教育焦虑才会真正松开。",
                "note": "摘自原文导语"
              },
              {
                "type": "section-block",
                "sectionIndex": 0,
                "callouts": [
                  {
                    "type": "tip",
                    "title": "作者提醒",
                    "body": "这类提醒应保留在正文对应 section 里，而不是改写成普通段落。"
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    {
      "id": "tutorial-cards",
      "manifest": {
        "id": "tutorial-cards",
        "label": "教程卡片型",
        "order": 2,
        "version": "2026.03.25-alpha.1",
        "selectionValue": "tutorial-cards",
        "defaultColorPalette": "ocean-blue",
        "promptMode": "tutorial-cards",
        "fallbackPolicy": "tutorial-structured",
        "renderProfile": "tutorial-cards",
        "allowedBlocks": [
          "hero",
          "part-nav",
          "lead-quote",
          "case-block",
          "section-block",
          "phone-frame",
          "cta-card"
        ],
        "supportsImages": true,
        "providerStrategy": "require-ai",
        "recommendedArticleTypes": [
          "tutorial",
          "case-study",
          "product-intro",
          "workflow"
        ],
        "description": "更强调章节编号、信息卡与截图展示，适合教程、清单和案例拆解。"
      },
      "prompt": "你正在生成“教程卡片型”公众号排版。\n\n目标：\n- 强化结构感、步骤感、案例感。\n- 可以积极使用 hero、part-nav、lead-quote、case-block。\n- section-block 仍然优先承载正文，但整体需要更像“教程精修稿”。\n- 如果有截图或界面图，优先考虑 hero 封面和 phone-frame。\n- 即使结构更强化，也要尽量保留原文章节中的 callout、代码块、表格、嵌套列表等特殊结构，不要为了卡片化而把它们压平。\n\n风格原则：\n- 用户应该一眼看出这是一篇教程或案例拆解。\n- 可以增加结构性块，但不要遗漏后半段内容。\n- 优先做“封面概览 -> 导语摘要 -> 分章节正文 -> 可选截图块”。",
      "blocks": {
        "preferredIntroBlocks": [
          "hero",
          "part-nav",
          "lead-quote"
        ],
        "optionalIntroBlocks": [],
        "preferredBodyBlocks": [
          "section-block",
          "case-block"
        ],
        "optionalBodyBlocks": [
          "phone-frame"
        ],
        "optionalTailBlocks": [
          "cta-card"
        ],
        "imageStrategy": "tutorial-forward"
      },
      "fallback": {
        "includeHero": true,
        "includePartNav": true,
        "includeLeadQuote": true,
        "includePhoneFrame": true,
        "includeCta": false,
        "heroVariant": "cover-right",
        "heroEyebrow": "AI Layout Draft",
        "galleryCaseLabel": "GALLERY",
        "galleryTitle": "配图补充",
        "preferSectionBlocks": true,
        "remainingImageStrategy": "sections-first",
        "maxSectionBlocks": 8
      },
      "skillDoc": "---\nname: tutorial-cards-layout\ndescription: 教程卡片型 skill。强调章节编号、结构化卡片、截图展示和信息扫描效率。\n---\n\n# Tutorial Cards Layout Skill\n\n这个 skill 用于把文章排成“教程精修稿”的样子。\n\n## Guardrails\n\n- 可以强化结构，不可以丢正文\n- 可以用 hero / part-nav / phone-frame\n- 正文仍优先 section-block\n- CTA 只能按需生成，不能默认加\n- `section-block` 里的特殊内容要尽量保留，包括 `callout`、代码块、表格、嵌套列表；可以增强结构，但不要把这些内容压平成普通段落",
      "examples": [
        {
          "name": "tutorial.json",
          "value": {
            "articleType": "tutorial",
            "selection": {
              "layoutFamily": "tutorial-cards",
              "colorPalette": "ocean-blue"
            },
            "resolved": {
              "layoutFamily": "tutorial-cards",
              "colorPalette": "ocean-blue"
            },
            "recommendedLayoutFamily": "tutorial-cards",
            "recommendedColorPalette": "ocean-blue",
            "title": "Obsidian 入门：给笔记打标签",
            "summary": "像教程精修稿一样结构清晰。",
            "blocks": [
              {
                "type": "hero",
                "eyebrow": "AI Layout Draft",
                "title": "Obsidian 入门：给笔记打标签",
                "subtitle": "让内容自己跳出来",
                "coverImageId": "image-1",
                "variant": "cover-right"
              },
              {
                "type": "part-nav",
                "items": [
                  {
                    "label": "PART 01",
                    "text": "标签是什么"
                  },
                  {
                    "label": "PART 02",
                    "text": "怎么用"
                  }
                ]
              },
              {
                "type": "section-block",
                "sectionIndex": 0,
                "sectionLabel": "PART 01",
                "title": "标签是什么",
                "callouts": [
                  {
                    "type": "tip",
                    "title": "先理解再操作",
                    "body": "教程型布局可以强化结构，但原文里的提示信息仍应作为 callout 保留。"
                  }
                ],
                "subsections": [
                  {
                    "title": "常见误区",
                    "level": 3,
                    "callouts": [
                      {
                        "type": "note",
                        "title": "注意",
                        "body": "不要把所有提示内容都压平成普通子段落。"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    {
      "id": "editorial-lite",
      "manifest": {
        "id": "editorial-lite",
        "label": "轻杂志型",
        "order": 3,
        "version": "2026.03.25-alpha.1",
        "selectionValue": "editorial-lite",
        "defaultColorPalette": "graphite-rose",
        "promptMode": "editorial-lite",
        "fallbackPolicy": "editorial-flow",
        "renderProfile": "editorial-lite",
        "allowedBlocks": [
          "hero",
          "part-nav",
          "lead-quote",
          "case-block",
          "section-block",
          "phone-frame",
          "cta-card"
        ],
        "supportsImages": true,
        "providerStrategy": "require-ai",
        "recommendedArticleTypes": [
          "editorial",
          "brand-story",
          "opinion"
        ],
        "description": "偏编辑感的留白与图文节奏，适合观点、经验与品牌表达类内容。"
      },
      "prompt": "你正在生成“轻杂志型”公众号排版。\n\n目标：\n- 让文章更像编辑排版过的内容稿，而不是教程模板。\n- 优先体现标题气质、导语节奏、留白和图文呼吸感。\n- 弱化教程式导航和手机框。\n- 如果原文适合，可用强 lead-quote、masthead 式 hero、较轻的章节节奏。\n- 正文区块依然要保真，原文里的 callout、代码块、表格、嵌套列表等特殊结构应优先保留在对应 section-block / subsection 中。\n\n风格原则：\n- 更少教程感，更强 editorial 感。\n- 不要把每一段都卡片化。\n- 允许图文穿插，但不牺牲正文完整性。",
      "blocks": {
        "preferredIntroBlocks": [
          "hero",
          "lead-quote"
        ],
        "optionalIntroBlocks": [
          "part-nav"
        ],
        "preferredBodyBlocks": [
          "section-block",
          "case-block"
        ],
        "optionalBodyBlocks": [],
        "optionalTailBlocks": [
          "cta-card"
        ],
        "imageStrategy": "editorial-forward"
      },
      "fallback": {
        "includeHero": true,
        "includePartNav": false,
        "includeLeadQuote": true,
        "includePhoneFrame": false,
        "includeCta": false,
        "heroVariant": "cover-left",
        "heroEyebrow": "Editorial Layout",
        "galleryCaseLabel": "IMAGES",
        "galleryTitle": "图像摘录",
        "preferSectionBlocks": true,
        "remainingImageStrategy": "sections-first",
        "maxSectionBlocks": 5
      },
      "skillDoc": "---\nname: editorial-lite-layout\ndescription: 轻杂志型 skill。强调导语、留白、编辑感节奏和更克制的图文关系。\n---\n\n# Editorial Lite Layout Skill\n\n这个 skill 用于把文章排成“轻杂志型”的内容稿。\n\n## Guardrails\n\n- 强调节奏和留白，不要每段都卡片化\n- 不默认教程导航\n- 不默认手机壳\n- lead-quote 可以更强，但不能改写观点\n- `section-block` 依然要承担正文保真职责；原文里的 `callout`、代码块、表格、嵌套列表等特殊结构应尽量保留，不要为了 editorial 节奏把它们压平成普通文字",
      "examples": [
        {
          "name": "editorial.json",
          "value": {
            "articleType": "article",
            "selection": {
              "layoutFamily": "editorial-lite",
              "colorPalette": "graphite-rose"
            },
            "resolved": {
              "layoutFamily": "editorial-lite",
              "colorPalette": "graphite-rose"
            },
            "recommendedLayoutFamily": "editorial-lite",
            "recommendedColorPalette": "graphite-rose",
            "title": "写作经验复盘",
            "summary": "更有呼吸感、更像编辑稿。",
            "blocks": [
              {
                "type": "hero",
                "eyebrow": "Editorial Layout",
                "title": "写作经验复盘",
                "subtitle": "更轻、更有呼吸感的版式",
                "coverImageId": "image-1",
                "variant": "cover-left"
              },
              {
                "type": "lead-quote",
                "text": "写作的真正难点，从来不是表达，而是删改。",
                "note": "摘自原文观点句"
              },
              {
                "type": "section-block",
                "sectionIndex": 0,
                "title": "删改比落笔更重要",
                "callouts": [
                  {
                    "type": "note",
                    "title": "编者按",
                    "body": "即使是轻杂志型，也应保留原文里的提示、说明和注记，而不是把它们改写成普通正文。"
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  ]
};
